[package]
name = "mandelbrot_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.8", features = ["rayon"] }
rayon = "1.8.1"

